flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%env(resolve:STORAGE_PATH)%'
                permissions:
                    file: { public: 0640, private: 0600 }
                    dir: { public: 0750, private: 0700 }
