framework:
    messenger:
        failure_transport: failed

        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: '%env(MESSENGER_TRANSPORT_DSN)%?stream=failed'

        routing:
            App\Ingest\Message\IngestArchive: async
            App\Ingest\Message\GenerateDerivative: async
            App\Ingest\Message\GenerateChapterCovers: async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
