services:
  php:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION}
    command: php -S 0.0.0.0:8000 -t public
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://app:app@database:5432/app?serverVersion=${POSTGRES_VERSION}&charset=utf8
      MESSENGER_TRANSPORT_DSN: redis://redis:6379/messages
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started

  database:
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "app", "-U", "app"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  redis:
    image: redis:${REDIS_VERSION}-alpine

volumes:
  database_data:
