<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261002115142 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE TABLE chapter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number NUMERIC(6, 1) NOT NULL, direction VARCHAR(16) NOT NULL, title VARCHAR(255) DEFAULT NULL, published BOOLEAN DEFAULT false NOT NULL, work_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX chapter_work_number ON chapter (work_id, number)');
        $this->addSql('CREATE INDEX IDX_F981B52EBB3453DB ON chapter (work_id)');
        $this->addSql('CREATE TABLE page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, original_key VARCHAR(255) NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, status VARCHAR(16) NOT NULL, chapter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX page_chapter_position ON page (chapter_id, position)');
        $this->addSql('CREATE INDEX IDX_140AB620579F4768 ON page (chapter_id)');
        $this->addSql('CREATE TABLE work (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, type VARCHAR(16) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_534E6880989D9B62 ON work (slug)');
        $this->addSql('ALTER TABLE chapter ADD CONSTRAINT FK_F981B52EBB3453DB FOREIGN KEY (work_id) REFERENCES work (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB620579F4768 FOREIGN KEY (chapter_id) REFERENCES chapter (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chapter DROP CONSTRAINT FK_F981B52EBB3453DB');
        $this->addSql('ALTER TABLE page DROP CONSTRAINT FK_140AB620579F4768');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE chapter');
        $this->addSql('DROP TABLE page');
        $this->addSql('DROP TABLE work');
    }
}
